import type { Metadata } from "next";
// DOUBT: Why is globals.css not recognized properly by typescript?
//@ts-expect-error This works actually
import "./globals.css";

// TODO: Replace later when you are connected to better internet
// import {JetBrains_Mono } from "next/font/google";
// const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-sans'});

import localFont from 'next/font/local'
const local_jetbrains_mono = localFont({
  src: '../public/JetBrainsMono-VariableFont_wght.ttf'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${local_jetbrains_mono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
